// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanuvfmrDSlVxfm5F9t1m6JdWk9Cfsfz4',
    appId: '1:719940192875:web:900175db233f9b9ceebf2e',
    messagingSenderId: '719940192875',
    projectId: 'systemlogin-b9287',
    authDomain: 'systemlogin-b9287.firebaseapp.com',
    storageBucket: 'systemlogin-b9287.appspot.com',
    measurementId: 'G-S8ZTW03KTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFqSVdzOUbgXPJBkU5tkoQs1xtvyPX4U',
    appId: '1:719940192875:android:d4cd3db685a3aef4eebf2e',
    messagingSenderId: '719940192875',
    projectId: 'systemlogin-b9287',
    storageBucket: 'systemlogin-b9287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LtGfu-CKsYQZou1moMVANuNee07A_7M',
    appId: '1:719940192875:ios:d4583bce7606dbc1eebf2e',
    messagingSenderId: '719940192875',
    projectId: 'systemlogin-b9287',
    storageBucket: 'systemlogin-b9287.appspot.com',
    iosClientId: '719940192875-rnpg5jjlia2lmshk01e3cgefbqdfo990.apps.googleusercontent.com',
    iosBundleId: 'com.example.comSgSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-LtGfu-CKsYQZou1moMVANuNee07A_7M',
    appId: '1:719940192875:ios:d4583bce7606dbc1eebf2e',
    messagingSenderId: '719940192875',
    projectId: 'systemlogin-b9287',
    storageBucket: 'systemlogin-b9287.appspot.com',
    iosClientId: '719940192875-rnpg5jjlia2lmshk01e3cgefbqdfo990.apps.googleusercontent.com',
    iosBundleId: 'com.example.comSgSystem',
  );
}
