// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKnSdb5MiT1o1K8f22pRZzZn2QpVFz694',
    appId: '1:885378731990:web:96acd2a1c7e687bf9d5e77',
    messagingSenderId: '885378731990',
    projectId: 'comsgsystem',
    authDomain: 'comsgsystem.firebaseapp.com',
    storageBucket: 'comsgsystem.appspot.com',
    measurementId: 'G-SGE46D65MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3k6NhXcPiGjy1uS6IFFkOjx4H3JVeSco',
    appId: '1:885378731990:android:c363f3097f0dc3379d5e77',
    messagingSenderId: '885378731990',
    projectId: 'comsgsystem',
    storageBucket: 'comsgsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8whjoQ_Zw0I7M9m9pe37Cn2DVk9pQ4_0',
    appId: '1:885378731990:ios:08f36bb3562f7c579d5e77',
    messagingSenderId: '885378731990',
    projectId: 'comsgsystem',
    storageBucket: 'comsgsystem.appspot.com',
    iosBundleId: 'com.example.comSgSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8whjoQ_Zw0I7M9m9pe37Cn2DVk9pQ4_0',
    appId: '1:885378731990:ios:08f36bb3562f7c579d5e77',
    messagingSenderId: '885378731990',
    projectId: 'comsgsystem',
    storageBucket: 'comsgsystem.appspot.com',
    iosBundleId: 'com.example.comSgSystem',
  );
}
